compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
