name: 📦 Build and test npm Package
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Checkout all branches and tags
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
          cache: 'yarn'

      # Install dependencies
      - run: yarn

      # Run tests
      - name: 🧪 Run tests
        run: yarn run test

      # Build packages
      - name: Build @kaoto/forms
        run: yarn run build
