name: 📦 Build and publish npm Package
# Event for the workflow
on:
  # 👇 Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    if: github.repository == 'KaotoIO/forms' && github.actor != 'renovate[bot]'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.KAOTO_RELEASE_APP_ID }}
          private-key: ${{ secrets.KAOTO_RELEASE_APP_KEY }}

      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Checkout all branches and tags
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
          cache: 'yarn'

      # Install dependencies
      - run: yarn

      # Run tests
      - name: 🧪 Run tests
        run: yarn run test

      # Build packages
      - name: Build @kaoto/forms
        run: yarn run build

      # Version and publish
      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.KAOTO_NEXT_NPM_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          yarn publish
